
server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/minghanqiu/springcloud-config.git #github仓库上面的git仓库名字
          ##搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master

  #rabbit相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册进eureka

#暴露监控端点 用于动态刷新
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"